DELETE  http://localhost:49205/api/product/57
###
GET http://localhost:49205/api/users/active/customer
###
GET http://localhost:49205/api/product/popular
###
GET http://localhost:49205/api/holding/1
###
GET http://localhost:49205/api/company
###
GET http://localhost:49205/api/category/1
###
GET http://localhost:49205/api/product/37/user/1
###

POST http://localhost:49205/api/users/login
Content-Type: application/json

{
  Username: "bos",
  Password: "bos"
}
###
GET  http://localhost:49205/api/chat/user/35
###

GET  http://localhost:49205/api/chat/room/aaaa/user/33
###
GET  http://localhost:49205/api/chats/unread/user/35
###

POST http://localhost:49205/api/chats
Content-Type: application/json

{
    RoomId: "bbbb",
    SenderId: 35,
    ReceiverId: 33,
    Date: "2017",
    Message: "32 is test message"
}
###

POST http://localhost:49205/api/chats
Content-Type: application/json

{
    "roomId": "bbbb",
    "senderId": 33,
    "receiverId": 35,
    "date": "2017",
    "message": "33 now test message"
}
###

POST http://localhost:49205/api/users/register
Content-Type: application/json

{
  Username: "reg",
  Password: "reg",
  IdNumber: "0001",
  IdType: 1,
  Name: "reg",
  Email: "reg@reg.com",
  Address: "reg",
  Occupation: "reg",
  Handphone: "reg",
  JobTitle: "reg",
  CompanyId: 1,
}

###
POST http://localhost:49205/api/product/empty
Content-Type: application/json
Cache-Control: no-cache

{}

###
GET http://kombit.org/api/product/interaction/user/1
Cache-Control: no-cache
###
GET http://kombit.org/api/product/user/2