GET http://localhost:49205/api/users/active/supplier
###
GET http://localhost:49205/api/users/active/customer
###
GET http://localhost:49205/api/product/popular
###
GET http://localhost:49205/api/holding/1
###
GET http://localhost:49205/api/company
###
GET http://localhost:49205/api/category/1
###
GET http://localhost:49205/api/product
###

POST http://localhost:49205/api/users/login
Content-Type: application/json

{
  Username: "bos",
  Password: "bos"
}
###

POST http://localhost:49205/api/users/register
Content-Type: application/json

{
  Username: "reg",
  Password: "reg",
  IdNumber: "0001",
  IdType: 1,
  Name: "reg",
  Email: "reg@reg.com",
  Address: "reg",
  Occupation: "reg",
  Handphone: "reg",
  JobTitle: "reg",
  CompanyId: 1,
}

###
POST http://localhost:49205/api/product
Content-Type: application/json
Cache-Control: no-cache

{
  VideoPath: "reg.reg/reg.ix",
  FotoPath: "reg/reg.ix",
  FotoName: "reg.ix", 
  Credentials: "what is reg",
  Price: 1000,
  IsIncludePrice: true,
  Description: "reg is reg",
  ProductName: "reg1",
  CategoryId: 1,
  HoldingId: 1,
  CompanyId: 1,
  UserId: 1,
}

###
GET http://kombit.org/api/product/interaction/user/1
Cache-Control: no-cache
###
GET http://kombit.org/api/product/user/2